# Generated by Django 2.2.7 on 2019-11-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='type',
            new_name='muscle',
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_type', models.CharField(default='no name', max_length=100)),
                ('rep', models.CharField(default='no reps', max_length=100)),
                ('weight', models.CharField(default='no weight', max_length=100)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='workout.Workout')),
            ],
        ),
    ]
