# Generated by Django 2.2.7 on 2019-11-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20191106_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='Coop', max_length=100),
            preserve_default=False,
        ),
    ]
